-- Workspace -----------------------------------------------------------------------------------------------------------
workspace "magnolia"
    architecture "x86_64"
    language "c++"
    cppdialect "c++20"
    toolset "clang"
    configurations { "debug", "release" }
    location "build"
    staticruntime "on"
    
    -- Output directories
    targetdir ("build/%{cfg.system}/%{cfg.buildcfg}/bin/%{prj.name}")
    objdir ("build/%{cfg.system}/%{cfg.buildcfg}/obj/%{prj.name}")

    -- @TODO: finish windows 
    -- @TODO: some cmakes also compiles the examples/tests. We want to compile only the libs.

    -- @TODO: remaining libs configurations
    target_libdir = "build/" .. os.host() .. "/" .. "debug/bin"
    obj_libdir = "build/" .. os.host() .. "/" .. "debug/obj"
    
    engine_libdir =
    {
        target_libdir .. "/fmt",
        target_libdir .. "/sdl",
        target_libdir .. "/vulkan",
        target_libdir .. "/assimp",
        target_libdir .. "/meshoptimizer",
        target_libdir .. "/bullet",
        target_libdir .. "/freetype",
        target_libdir .. "/soloud"
    }

    engine_lib_includes =
    {
        "libs",
        "libs/sdl/include",
        "libs/fmt/include",
        "libs/vulkan/include",
        "libs/vkbootstrap/src",
        "libs/vma/include",
        "libs/assimp/include",
        "libs/glm",
        "libs/stb",
        "libs/spirv_reflect",
        "libs/json/single_include",
        "libs/meshoptimizer/src",
        "libs/bullet/src",
        "libs/freetype/include",
        "libs/soloud/include",

        -- @TODO: this is necessary because 'config.h' is generated by the cmake
        obj_libdir .. "/assimp/include"
    }

    engine_lib_links = 
    {
        "vulkan",
        "fmt", "SDL2", "SDL2main", "assimp", "meshoptimizer",
        "BulletDynamics", "BulletInverseDynamics", "BulletCollision",
        "Bullet3Common", "Bullet3Dynamics", "Bullet3Collision", "Bullet3Geometry", 
        "LinearMath",
        "freetype",
        "soloud"
    }

    -- @NOTE: don't use LTO on debug, it might interfere with ClangBuildAnalyzer
    build_flags =
    {
        "LinkTimeOptimization"
    }

    defines
    {
        "VULKAN_HPP_NAMESPACE=vk",
        "GLM_FORCE_QUAT_DATA_WXYZ"
    }

    linkoptions
    {
        -- Change your preferred linker here (or comment this line to use the system default)
        "-fuse-ld=mold -Wl,-v",

        -- For some reason, premake is having trouble finding assimp
        "-Wl,-R" .. target_libdir .. "/assimp"
    }

-- Engine --------------------------------------------------------------------------------------------------------------
project "magnolia"
    targetname ("%{prj.name}")
    kind "sharedlib"

    pchheader "%{prj.name}/src/pch.hpp"
    pchsource "%{prj.name}/src/pch.cpp"

    files
    {
        "%{prj.name}/src/**.hpp",
        "%{prj.name}/src/**.cpp",
        "%{prj.name}/include/**.hpp",
        "libs/spirv_reflect/spirv_reflect.h",
        "libs/spirv_reflect/spirv_reflect.cpp",
        "libs/json/single_include/nlohmann/json.hpp",
        "libs/vkbootstrap/src/VkBootstrap.h",
        "libs/vkbootstrap/src/VkBootstrapDispatch.h",
        "libs/vkbootstrap/src/VkBootstrap.cpp"
    }

    includedirs
    {
        "%{prj.name}/src",
        "%{prj.name}/include",

        engine_lib_includes
    }

    defines
    {
        "VULKAN_HPP_NO_EXCEPTIONS",
        "MAG_BUILD_SHARED"
    }

    links
    {
        engine_lib_links
    }

    libdirs
    { 
        engine_libdir
    }

    dependson
    {
        "fmt",
        "sdl",
        "vulkan",
        "assimp",
        "meshoptimizer",
        "bullet",
        "freetype",
        "soloud"
    }

    filter "system:linux"
        pic "on"

    filter "system:windows"
        systemversion "latest"

        defines
        {
            "_CRT_SECURE_NO_WARNINGS"
        }
        
    filter "configurations:debug"
        buildoptions { "-Wall", "-Wextra", "-ftime-trace", "-fno-exceptions", "-fvisibility=hidden" }
        defines { "MAG_CONFIG_DEBUG=1", "MAG_ASSERTIONS_ENABLED=1", "MAG_PROFILE_ENABLED=1" }
        symbols "on" -- '-g'
        optimize "off" -- '-O0'
        runtime "debug"

    filter "configurations:release"
        buildoptions { "-fno-exceptions", "-fvisibility=hidden" }
        defines { "NDEBUG", "MAG_CONFIG_RELEASE=1", "MAG_PROFILE_ENABLED=1" }
        flags { build_flags }
        symbols "off"
        optimize "full" -- '-O3'
        runtime "release"

-- Client Application --------------------------------------------------------------------------------------------------
project "test_game"
    targetname ("%{prj.name}")
    kind "consoleapp"

    files
    {
        "%{prj.name}/src/**.hpp",
        "%{prj.name}/src/**.cpp"
    }

    includedirs 
    { 
        "%{prj.name}/src",
        "magnolia/include",
        "libs/fmt/include", -- @TODO: remove when fmt is removed
        "libs/json/single_include"
    }

    libdirs
    { 
        target_libdir .. "/fmt" -- @TODO: remove when fmt is removed
    }

    links
    {
        "magnolia", 
        "fmt" -- @TODO: remove when fmt is removed
    }

    dependson
    {
        "magnolia"
    }

    filter "system:linux"
        pic "on"

    filter "system:windows"
        systemversion "latest"

        defines
        {
            "_CRT_SECURE_NO_WARNINGS"
        }
        
    filter "configurations:debug"
        buildoptions { "-Wall", "-Wextra", "-ftime-trace", "-fno-exceptions" }
        defines { "MAG_CONFIG_DEBUG=1", "MAG_ASSERTIONS_ENABLED=1", "MAG_PROFILE_ENABLED=1" }
        symbols "on" -- '-g'
        optimize "off" -- '-O0'
        runtime "debug"

    filter "configurations:release"
        buildoptions { "-Wall", "-Wextra", "-fno-exceptions" }
        defines { "NDEBUG", "MAG_CONFIG_RELEASE=1" }
        flags { build_flags }
        symbols "off"
        optimize "full" -- '-O3'
        runtime "release"

-- Libs ----------------------------------------------------------------------------------------------------------------

-- Checks if a file exists
function exists(filePath)
    local file = io.open(filePath, "r")
    if file then
        file:close()
        return true
    else
        return false
    end
end

-- Execute a shell command
function execute_command(command)
    local file = io.popen(command)
    local output = file:read("*a")
    file:close()
    return output
end

-- Get number of cores (linux only)
function number_of_cores()
    result = tonumber(execute_command("nproc"))
    return result
end

-- Build a cmake project
function build_cmake_project(project_name, libs_info)
    project_bin_dir = target_libdir .. "/" .. project_name
    project_obj_dir = obj_libdir .. "/" .. project_name
    
    print("Building " .. project_name .. "...")

    -- Check if any of the libraries need to be built
    local need_build = false
    for _, lib_info in ipairs(libs_info) do
        local project_bin_path = project_bin_dir .. "/" .. lib_info.name
        if not exists(project_bin_path) then
            need_build = true
            print(project_bin_path .. " is missing, recompiling...")
            break
        else
            print("Found " .. project_bin_path)
        end
    end
    
    if not need_build then
        os.execute("echo All libs available, skipping " .. project_name .. " compilation...")
        return
    end

    os.execute("mkdir -p " .. project_bin_dir)
    os.execute("mkdir -p " .. project_obj_dir)
    os.execute("cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON -S libs/" .. project_name .. " -B " .. project_obj_dir)
    os.execute("cd " .. project_obj_dir .. " && make -j " .. number_of_cores())
    
    -- Copy all libraries to the bin directory
    for _, lib_info in ipairs(libs_info) do
        local project_obj_path = project_obj_dir .. "/" .. lib_info.dir .. "/" .. lib_info.name
        local project_bin_path = project_bin_dir .. "/" .. lib_info.name
        os.execute("cp " .. project_obj_path .. " " .. project_bin_path)
    end
end

-- vulkan --------------------------------------------------------------------------------------------------------------
project "vulkan"
    kind "none"

    vulkan_libs = { "libvulkan.so", "libvulkan.so.1", "libvulkan.so.1.3.268" }

    if os.host() == "windows" then
        os.execute("echo @TODO: WINDOWS VULKAN COPY")
    end

    local vulkan_dir = target_libdir .. "/vulkan"

    os.execute("mkdir -p " .. vulkan_dir)

    -- Simply copy vulkan libs to the build folder
    for _, vulkan_lib in ipairs(vulkan_libs) do
        local vulkan_bin_path = vulkan_dir .. "/" .. vulkan_lib
        os.execute("cp -u ext/linux/" .. vulkan_lib .. " " .. vulkan_bin_path)
    end

-- fmt -----------------------------------------------------------------------------------------------------------------
project "fmt"
    kind "none"
    build_cmake_project("fmt", {
        {name = "libfmt.a", dir = ""}
    })
        
-- sdl -----------------------------------------------------------------------------------------------------------------
project "sdl"
    kind "none"
    build_cmake_project("sdl", {
        {name = "libSDL2.a", dir = ""},
        {name = "libSDL2main.a", dir = ""}
    })

-- assimp --------------------------------------------------------------------------------------------------------------
project "assimp"
    kind "none"
    build_cmake_project("assimp", {
        {name = "libassimp.so", dir = "bin"},
        {name = "libassimp.so.6", dir = "bin"},
        {name = "libassimp.so.6.0.2", dir = "bin"}
    })
    
-- meshoptimizer -------------------------------------------------------------------------------------------------------
project "meshoptimizer"
    kind "none"
    build_cmake_project("meshoptimizer", {
        {name = "libmeshoptimizer.a", dir = ""}
    })
    
-- bullet --------------------------------------------------------------------------------------------------------------
project "bullet"
    kind "none"
    build_cmake_project("bullet", {
        {name = "libBulletDynamics.a", dir = "src/BulletDynamics"},
        {name = "libBulletInverseDynamics.a", dir = "src/BulletInverseDynamics"},
        {name = "libBulletCollision.a", dir = "src/BulletCollision"},
        {name = "libBullet3Common.a", dir = "src/Bullet3Common"},
        {name = "libBullet3Dynamics.a", dir = "src/Bullet3Dynamics"},
        {name = "libBullet3Collision.a", dir = "src/Bullet3Collision"},
        {name = "libBullet3Geometry.a", dir = "src/Bullet3Geometry"},
        {name = "libLinearMath.a", dir = "src/LinearMath"}
    })

-- freetype ------------------------------------------------------------------------------------------------------------
project "freetype"
    kind "none"
    build_cmake_project("freetype", {
        {name = "libfreetype.a", dir = ""}
    })

-- soloud --------------------------------------------------------------------------------------------------------------
project "soloud"
    kind "staticlib"
    language "c++"
    cppdialect "c++20"

    includedirs
    {
        "libs/soloud/include",
        engine_lib_includes -- SDL2
    }

    files
    {
        "libs/soloud/include/**.h",
        "libs/soloud/src/core/**.cpp",
        
        "libs/soloud/src/audiosource/speech/**.h",
        "libs/soloud/src/audiosource/speech/**.cpp",
        "libs/soloud/src/audiosource/openmpt/**.c",
        "libs/soloud/src/audiosource/openmpt/**.cpp",
        "libs/soloud/src/audiosource/wav/**.h",
        "libs/soloud/src/audiosource/wav/**.c",
        "libs/soloud/src/audiosource/wav/**.cpp",
        "libs/soloud/src/backend/sdl/soloud_sdl2.cpp",
        "libs/soloud/src/backend/sdl/soloud_sdl2_dll.c"
    }

    defines
    {
        -- Choose audio backend
        "WITH_SDL2"
    }

    filter "system:linux"
        pic "on"
        systemversion "latest"
        staticruntime "on"
