-- Workspace -----------------------------------------------------------------------------------------------------------
workspace "magnolia"
    architecture "x86_64"
    language "c++"
    cppdialect "c++23"
    toolset "clang"
    configurations { "debug", "release" }
    location "build"
    staticruntime "on"
    
    -- Output directories
    targetdir ("build/%{cfg.system}/%{cfg.buildcfg}/bin/%{prj.name}")
    objdir ("build/%{cfg.system}/%{cfg.buildcfg}/obj/%{prj.name}")

    -- @TODO: finish windows

    -- @TODO: remaining libs configurations
    target_libdir = "build/" .. os.host() .. "/" .. "debug/bin"
    obj_libdir = "build/" .. os.host() .. "/" .. "debug/obj"
    
    engine_libdir =
    {
        target_libdir .. "/sdl",
        target_libdir .. "/vkbootstrap",
        target_libdir .. "/spirv_reflect",
        target_libdir .. "/vulkan",
        target_libdir .. "/assimp",
        target_libdir .. "/meshoptimizer",
        target_libdir .. "/freetype",
        target_libdir .. "/soloud",
        target_libdir .. "/imgui",
        target_libdir .. "/jolt"
    }

    engine_lib_includes =
    {
        "libs",
        "libs/sdl/include",
        "libs/vulkan/include",
        "libs/vkbootstrap/src",
        "libs/vma/include",
        "libs/assimp/include",
        "libs/glm",
        "libs/stb",
        "libs/spirv_reflect",
        "libs/json/single_include",
        "libs/meshoptimizer/src",
        "libs/freetype/include",
        "libs/soloud/include",
        "libs/imgui",
        "libs/jolt",

        -- @TODO: this is necessary because 'config.h' is generated by the cmake
        obj_libdir .. "/assimp/include"
    }

    engine_lib_links = 
    {
        "vulkan",
        "vk-bootstrap",
        "spirv-reflect-static",
        "SDL3", 
        "assimp",
        "meshoptimizer",
        "freetype",
        "soloud",
        "imgui",
        "Jolt"
    }

    defines
    {
        "VULKAN_HPP_NAMESPACE=vk",
        "GLM_FORCE_QUAT_DATA_WXYZ",
        "GLM_ENABLE_EXPERIMENTAL",
        "JPH_PROFILE_ENABLED",
        "JPH_DEBUG_RENDERER",
        "JPH_OBJECT_STREAM"
    }

    linkoptions
    {
        -- Change your preferred linker here (or comment this line to use the system default)
        "-fuse-ld=mold -Wl,-v"
    }

-- Engine --------------------------------------------------------------------------------------------------------------
project "magnolia"
    targetname ("%{prj.name}")
    kind "sharedlib"

    pchheader "%{prj.name}/src/pch.hpp"
    pchsource "%{prj.name}/src/pch.cpp"

    files
    {
        "%{prj.name}/src/**.hpp",
        "%{prj.name}/src/**.cpp",
        "%{prj.name}/include/**.hpp"
    }

    includedirs
    {
        "%{prj.name}/src",
        "%{prj.name}/include",

        engine_lib_includes
    }

    defines
    {
        "VULKAN_HPP_NO_EXCEPTIONS",
        "MAG_BUILD_SHARED"
    }

    links
    {
        engine_lib_links
    }

    libdirs
    { 
        engine_libdir
    }

    dependson
    {
        "sdl",
        "vulkan",
        "vkbootstrap",
        "spirv_reflect",
        "assimp",
        "meshoptimizer",
        "freetype",
        "soloud",
        "imgui",
        "jolt"
    }

    filter "system:linux"
        pic "on"

    filter "system:windows"
        systemversion "latest"

        defines
        {
            "_CRT_SECURE_NO_WARNINGS"
        }
        
    filter "configurations:debug"
        buildoptions { "-Wall", "-Wextra", "-ftime-trace", "-fno-exceptions", "-fvisibility=hidden" }
        defines { "MAG_CONFIG_DEBUG=1", "MAG_ASSERTIONS_ENABLED=1", "MAG_PROFILE_ENABLED=1" }
        symbols "on" -- '-g'
        optimize "off" -- '-O0'
        runtime "debug"

    filter "configurations:release"
        buildoptions { "-fno-exceptions", "-fvisibility=hidden" }
        defines { "NDEBUG", "MAG_CONFIG_RELEASE=1", "MAG_PROFILE_ENABLED=1" }
        linktimeoptimization ("fast")
        symbols "off"
        optimize "full" -- '-O3'
        runtime "release"

-- Client Application --------------------------------------------------------------------------------------------------
project "test_game"
    targetname ("%{prj.name}")
    kind "consoleapp"

    files
    {
        "%{prj.name}/src/**.hpp",
        "%{prj.name}/src/**.cpp"
    }

    includedirs 
    { 
        "%{prj.name}/src",
        "magnolia/include",
        "libs/json/single_include",
        "libs/glm"
    }

    links
    {
        "magnolia"
    }

    dependson
    {
        "magnolia"
    }

    filter "system:linux"
        pic "on"

    filter "system:windows"
        systemversion "latest"

        defines
        {
            "_CRT_SECURE_NO_WARNINGS"
        }
        
    filter "configurations:debug"
        buildoptions { "-Wall", "-Wextra", "-ftime-trace", "-fno-exceptions" }
        defines { "MAG_CONFIG_DEBUG=1", "MAG_ASSERTIONS_ENABLED=1", "MAG_PROFILE_ENABLED=1" }
        symbols "on" -- '-g'
        optimize "off" -- '-O0'
        runtime "debug"

    filter "configurations:release"
        buildoptions { "-Wall", "-Wextra", "-fno-exceptions" }
        defines { "NDEBUG", "MAG_CONFIG_RELEASE=1" }
        linktimeoptimization ("fast")
        symbols "off"
        optimize "full" -- '-O3'
        runtime "release"

-- Libs ----------------------------------------------------------------------------------------------------------------

local colors = {
    Reset = "\27[0m",
    Red = "\27[1;31m",
    Green = "\27[1;32m",
    Yellow = "\27[1;33m",
    Blue = "\27[1;34m",
    Purple = "\27[1;35m",
    White = "\27[1;37m"
}

-- Checks if a file exists
function exists(filePath)
    local file = io.open(filePath, "r")
    if file then
        file:close()
        return true
    else
        return false
    end
end

-- Execute a shell command
function execute_command(command)
    local file = io.popen(command)
    local output = file:read("*a")
    file:close()
    return output
end

-- Get number of cores (linux only)
function number_of_cores()
    result = tonumber(execute_command("nproc"))
    return result
end

-- Build a cmake project
function build_cmake_project(project_name, cmake_dir, libs_info, flags)
    project_bin_dir = target_libdir .. "/" .. project_name
    project_obj_dir = obj_libdir .. "/" .. project_name
    
    print(colors.Purple .. "Building " .. project_name .. colors.Reset)

    -- Check if any of the libraries need to be built
    local need_build = false
    for _, lib_info in ipairs(libs_info) do
        local project_bin_path = project_bin_dir .. "/" .. lib_info.name
        if not exists(project_bin_path) then
            need_build = true
            print(colors.Yellow .. project_bin_path .. " is missing, recompiling." .. colors.Reset)
            break
        else
            print(colors.Blue .. "Found " .. project_bin_path .. colors.Reset)
        end
    end
    
    if not need_build then
        print(colors.Green .. "All libs available, skipping " .. project_name .. " compilation." .. colors.Reset)
        return
    end

    os.execute("mkdir -p " .. project_bin_dir)
    os.execute("mkdir -p " .. project_obj_dir)
    os.execute("cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON " .. flags .. 
               " -S libs/" .. project_name .. "/" .. cmake_dir .. " -B " .. project_obj_dir)

    os.execute("cd " .. project_obj_dir .. " && make -j " .. number_of_cores())
    
    -- Copy all libraries to the bin directory
    for _, lib_info in ipairs(libs_info) do
        local project_obj_path = project_obj_dir .. "/" .. lib_info.dir .. "/" .. lib_info.name
        local project_bin_path = project_bin_dir .. "/" .. lib_info.name
        os.execute("cp " .. project_obj_path .. " " .. project_bin_path)
    end
end

-- vulkan --------------------------------------------------------------------------------------------------------------
project "vulkan"
    kind "none"

    vulkan_libs = { "libvulkan.so", "libvulkan.so.1", "libvulkan.so.1.3.268" }

    if os.host() == "windows" then
        os.execute("echo @TODO: WINDOWS VULKAN COPY")
    end

    local vulkan_dir = target_libdir .. "/vulkan"

    os.execute("mkdir -p " .. vulkan_dir)

    -- Simply copy vulkan libs to the build folder
    for _, vulkan_lib in ipairs(vulkan_libs) do
        local vulkan_bin_path = vulkan_dir .. "/" .. vulkan_lib
        os.execute("cp -u ext/linux/" .. vulkan_lib .. " " .. vulkan_bin_path)
    end
    
-- sdl -----------------------------------------------------------------------------------------------------------------
project "sdl"
    kind "none"
    build_cmake_project("sdl", "", {
        {name = "libSDL3.a", dir = ""}
    }, 
    "-DSDL_SHARED=OFF -DSDL_STATIC=ON -DSDL_EXAMPLES=OFF -DSDL_TESTS=OFF -DSDL_TEST_LIBRARY=OFF " ..
    "-DSDL_INSTALL=OFF -DSDL_DISABLE_INSTALL_DOCS=OFF -DSDL_INSTALL_TESTS=OFF")

-- vkbootstrap ---------------------------------------------------------------------------------------------------------
project "vkbootstrap"
    kind "none"
    build_cmake_project("vkbootstrap", "", {
        {name = "libvk-bootstrap.a", dir = ""}
    },
    "-DVK_BOOTSTRAP_POSITION_INDEPENDENT_CODE=ON -DVK_BOOTSTRAP_WERROR=ON -DVK_BOOTSTRAP_TEST=OFF")

-- spirv_reflect -------------------------------------------------------------------------------------------------------
project "spirv_reflect"
    kind "none"
    build_cmake_project("spirv_reflect", "", {
        {name = "libspirv-reflect-static.a", dir = ""}
    },
    "-DSPIRV_REFLECT_STATIC_LIB=ON -DSPIRV_REFLECT_EXAMPLES=OFF -DSPIRV_REFLECT_BUILD_TESTS=OFF " ..
    "-DSPIRV_REFLECT_INSTALL=OFF -DSPIRV_REFLECT_EXECUTABLE=OFF")

-- assimp --------------------------------------------------------------------------------------------------------------
project "assimp"
    kind "none"
    build_cmake_project("assimp", "", {
        {name = "libassimp.a", dir = "lib"}
    },
    "-DBUILD_SHARED_LIBS=OFF -DASSIMP_BUILD_TESTS=OFF -DASSIMP_INSTALL=OFF")
    
-- meshoptimizer -------------------------------------------------------------------------------------------------------
project "meshoptimizer"
    kind "none"
    build_cmake_project("meshoptimizer", "", {
        {name = "libmeshoptimizer.a", dir = ""}
    },
    "")

-- jolt ----------------------------------------------------------------------------------------------------------------
project "jolt"
    kind "none"
    build_cmake_project("jolt", "Build", {
        {name = "libJolt.a", dir = ""}
    },
    "-DCPP_RTTI_ENABLED=TRUE -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++ " ..
    "-DENABLE_INSTALL=OFF -DTARGET_UNIT_TESTS=OFF -DTARGET_HELLO_WORLD=OFF -DTARGET_PERFORMANCE_TEST=OFF " ..
    "-DTARGET_SAMPLES=OFF -DTARGET_VIEWER=OFF")

-- freetype ------------------------------------------------------------------------------------------------------------
project "freetype"
    kind "none"
    build_cmake_project("freetype", "", {
        {name = "libfreetype.a", dir = ""}
    },
    "")

-- soloud --------------------------------------------------------------------------------------------------------------
project "soloud"
    kind "staticlib"

    includedirs
    {
        "libs/soloud/include"
    }

    files
    {
        "libs/soloud/include/**.h",
        "libs/soloud/src/core/**.cpp",
        
        "libs/soloud/src/audiosource/speech/**.h",
        "libs/soloud/src/audiosource/speech/**.cpp",
        "libs/soloud/src/audiosource/openmpt/**.c",
        "libs/soloud/src/audiosource/openmpt/**.cpp",
        "libs/soloud/src/audiosource/wav/**.h",
        "libs/soloud/src/audiosource/wav/**.c",
        "libs/soloud/src/audiosource/wav/**.cpp",
        "libs/soloud/src/backend/miniaudio/miniaudio.h",
        "libs/soloud/src/backend/miniaudio/soloud_miniaudio.cpp"
    }

    defines
    {
        -- Choose audio backend
        "WITH_MINIAUDIO"
    }

    filter "system:linux"
        pic "on"
        systemversion "latest"
        staticruntime "on"

-- imgui ---------------------------------------------------------------------------------------------------------------
project "imgui"
	kind "staticlib"

	includedirs { ".", "libs/imgui", "libs/sdl/include" }

	files
	{
		"libs/imgui/imgui.h",
		"libs/imgui/imconfig.h",
		"libs/imgui/imgui_internal.h",
		"libs/imgui/imstb_rectpack.h",
		"libs/imgui/imstb_textedit.h",
		"libs/imgui/imstb_truetype.h",
		"libs/imgui/misc/cpp/imgui_stdlib.h",
		"libs/imgui/misc/cpp/imgui_stdlib.cpp",
		"libs/imgui/imgui.cpp",
		"libs/imgui/imgui_draw.cpp",
		"libs/imgui/imgui_tables.cpp",
		"libs/imgui/imgui_widgets.cpp",
		"libs/imgui/imgui_demo.cpp",

		"libs/imgui/backends/imgui_impl_sdl3.h",
		"libs/imgui/backends/imgui_impl_sdl3.cpp",
        "libs/imgui/backends/imgui_impl_sdlrenderer3.h",
        "libs/imgui/backends/imgui_impl_sdlrenderer3.cpp"
	}

	filter "system:linux"
		pic "on"
		systemversion "latest"
		staticruntime "on"