name: "Debug Build"
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Run the program
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - run: python3 build.py debug
      
        env:
          TAGS: ${{ inputs.tags }}
